apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-tag-lb-service-webhook
  namespace: hypershift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-tag-lb-service-webhook
  template:
    metadata:
      labels:
        app: aws-tag-lb-service-webhook
    spec:
      containers:
        - name: webhook
          image: quay.io/sjenning/aws-tag-lb-service-webhook:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: aws-tag-lb-service-webhook-serving-cert
