apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-tag-lb-service-webhook
  namespace: hypershift
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- name: aws-tag-lb-service-webhook.hypershift.svc
  admissionReviewVersions: ["v1beta1", "v1"]
  sideEffects: None
  clientConfig:
    service:
      name: aws-tag-lb-service-webhook
      namespace: hypershift
      path: "/mutate-service"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["services"]
