apiVersion: v1
kind: Service
metadata:
  name: aws-tag-lb-service-webhook
  namespace: hypershift
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: aws-tag-lb-service-webhook-serving-cert
spec:
  selector:
    app: aws-tag-lb-service-webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
